rule1: No hacking
rule2: No spamming
rule3: No kit mixing
rule4: No asking for ranks
rule5: No going out of map/greifing
rule6: No DDoS, Dox, or Dos of any sort
rule7: Respect all staff
rule8: No free for all in 1v1 arenas.
rule9: No advertising other servers
rule10: No combat logging
pvpmsg: You have equipped the PvP kit!
archermsg: You have equipped the Archer kit!
elitemsg: You have equipped the Elite kit!
blazemsg: You have equipped the Blaze kit!
fishermanmsg: You have equipped the Fisherman kit!
grandpamsg: You have equipped the Grandpa kit!
knightmsg: You have equipped the Knight kit!
scoutmsg: You have equipped the Scout kit!
snipermsg: You have equipped the Sniper kit!
switchermsg: You have equipped the Switcher kit!
tankmsg: You have equipped the Tank kit!
vikingmsg: You have equipped the Viking kit!
minermsg: You have equipped the Miner kit!
sonicmsg: You have equipped the Sonic kit!
dwarfmsg: You have equipped the Dwarf kit!
urgalmsg: You have equipped the Urgal kit!
votermsg: You have equipped the Voter kit!
vipermsg: You have equipped the Viper kit!
prefixmsg: MinecraftKits
cashonkill: 30