rule1: No hacking
rule2: No spamming
rule3: No kit mixing
rule4: No asking for ranks
rule5: No going out of map/greifing
rule6: No DDoS, Dox, or Dos of any sort
rule7: Respect all staff
rule8: No free for all in 1v1 arenas.
rule9: No advertising other servers
rule10: No combat logging
pvpmsg: You have equiped the PvP kit!
archermsg: You have equiped the Archer kit!
elitemsg: You have equiped the Elite kit!
blazemsg: You have equiped the Blaze kit!
fishermanmsg: You have equiped the Fisherman kit!
grandpamsg: You have equiped the Grandpa kit!
knightmsg: You have equiped the Knight kit!
scoutmsg: You have equiped the Scout kit!
snipermsg: You have equiped the Sniper kit!
switchermsg: You have equiped the Switcher kit!
tankmsg: You have equiped the Tank kit!
vikingmsg: You have equiped the Viking kit!
minermsg: You have equiped the Miner kit!
sonicmsg: You have equiped the Sonic kit!
prefixmsg: SonicKitPvP