name:  bKitPvP
main:  me.kitpvp.SonicKit.Main
version:  1.1
permissions:
    kitpvp.vip:
       children:
           kitpvp.pvp: true
           kitpvp.archer: true
           kitpvp.elite: true
           kitpvp.knight: true
           kitpvp.scout: true
           kitpvp.grandpa: true
    kitpvp.mvp:
       children:
           kitpvp.pvp: true
           kitpvp.archer: true
           kitpvp.elite: true
           kitpvp.knight: true
           kitpvp.scout: true
           kitpvp.grandpa: true
           kitpvp.switcher: true
           kitpvp.viking: true
           kitpvp.urgal: true
           kitpvp.dwarf: true
    kitpvp.pro:
       children:
           kitpvp.pvp: true
           kitpvp.archer: true
           kitpvp.elite: true
           kitpvp.knight: true
           kitpvp.scout: true
           kitpvp.grandpa: true
           kitpvp.switcher: true
           kitpvp.viking: true
           kitpvp.urgal: true
           kitpvp.dwarf: true
           kitpvp.sniper: true
           kitpvp.sonic: true
    kitpvp.titan:
       description: Use all MOTD commands.
       children:
           kitpvp.blaze: true
           kitpvp.pvp: true
           kitpvp.archer: true
           kitpvp.elite: true
           kitpvp.knight: true
           kitpvp.tank: true
           kitpvp.fisherman: true
           kitpvp.switcher: true
           kitpvp.sniper: true
           kitpvp.grandpa: true
           kitpvp.viking: true
           kitpvp.scout: true
           kitpvp.sonic: true
           kitpvp.urgal: true
           kitpvp.dwarf: true
           kitpvp.kits: true
commands:
   pvp:
     description: KitPvP.pvp
   archer:
     description: KitPvP.archer
   elite:
     description: KitPvP.elite
   knight:
     description: KitPvP.knight
   blaze:
     description: KitPvP.blaze
   tank:
     description: KitPvP.tank
   fisherman:
     description: KitPvP.fisherman
   switcher:
     description: KitPvP.switcher
   sniper:
     description: KitPvP.sniper
   grandpa:
     description: KitPvP.grandpa
   viking:
     description: KitPvP.viking
   scout:
     description: KitPvP.scout
   help:
     description: The help msg!
   pl:
     description: Plugins
   ?:
     description: Plugins
   kits:
     description: KitPvP.kits
   sonic:
     description: KitPvP.sonic
   urgal:
     description: KitPvP.urgal
   dwarf:
     description: KitPvP.dwarf
   soup:
     description: KitPvP.soup
   viper:
     description: Kitpvp.viper
   seeinv:
     description: Kitpvp.mod
   potpvp:
     description: Kitpvp.pot
   gm:
     description: Kitpvp.gm
   rules: